import sys
import os

# Override Database URL to SQLite for test running without postgres container
os.environ["DATABASE_URL"] = "sqlite:///./test_freightshare.db"

import json
from datetime import datetime, timedelta
from fastapi.testclient import TestClient

# Ensure app directory can be imported
sys.path.append(".")

from app.main import app
from app.database import SessionLocal, is_sqlite
from app.models import TrainSchedule
from seed_data import seed_database

def test_production_matching_flow():
    # 0. Initialize and seed database
    seed_database()

    client = TestClient(app)

    print("\n==============================================")
    print("📋 Checking API Health...")
    health_resp = client.get("/health")
    assert health_resp.status_code == 200
    print(f"  - Database type: {health_resp.json()['database']}")

    print("\n==============================================")
    print("🔑 Authenticating Users (Dev Mock Login)...")
    
    # Authenticate Driver
    driver_login = client.post("/auth/login", json={
        "id": "driver_arjun",
        "email": "arjun@freightshare.com",
        "role": "driver",
        "name": "Arjun Kumar"
    })
    assert driver_login.status_code == 200
    driver_token = driver_login.json()["access_token"]
    driver_headers = {"Authorization": f"Bearer {driver_token}"}
    print("  - Driver Authenticated successfully.")

    # Authenticate Shipper
    shipper_login = client.post("/auth/login", json={
        "id": "shipper_niranjan",
        "email": "niranjan@freightshare.com",
        "role": "shipper",
        "name": "Niranjan Shippers Ltd"
    })
    assert shipper_login.status_code == 200
    shipper_token = shipper_login.json()["access_token"]
    shipper_headers = {"Authorization": f"Bearer {shipper_token}"}
    print("  - Shipper Authenticated successfully.")

    print("\n==============================================")
    print("🚚 Checking Active Driver Trips...")
    trips_resp = client.get("/trips/?driver_id=driver_arjun", headers=shipper_headers)
    assert trips_resp.status_code == 200
    trips = trips_resp.json()
    assert len(trips) > 0
    trip_id = trips[0]["id"]
    print(f"  - Arjun's active Trip found. ID: {trip_id} ({trips[0]['origin_name']} -> {trips[0]['destination_name']})")
    print(f"    Available Capacity: Weight={trips[0]['remaining_weight_capacity']}kg, Volume={trips[0]['remaining_volume_capacity']} cu ft")

    print("\n==============================================")
    print("📦 Shipper Creates a Load (Vellore -> Bangalore, 500kg, 12 cu ft)...")
    load_resp = client.post("/loads/", json={
        "pickup_name": "Vellore",
        "dropoff_name": "Bangalore",
        "pickup_lat": 12.9165,
        "pickup_lng": 79.1325,
        "dropoff_lat": 12.9716,
        "dropoff_lng": 77.5946,
        "weight": 500.0,
        "volume": 12.0
    }, headers=shipper_headers)
    assert load_resp.status_code == 201, f"Load creation failed: {load_resp.text}"
    load_data = load_resp.json()
    load_id = load_data["id"]
    print(f"  - Load Request created successfully! ID: {load_id}")
    print(f"    From: {load_data['pickup_name']} -> To: {load_data['dropoff_name']} (Status: {load_data['status']})")

    print("\n==============================================")
    print("🔍 Fetching Proposed Matches for the Load (Spatial Overlap Results)...")
    matches_resp = client.get(f"/matches/?load_id={load_id}", headers=shipper_headers)
    assert matches_resp.status_code == 200, f"Match query failed: {matches_resp.text}"
    matches = matches_resp.json()
    
    print(f"  - Found {len(matches)} potential matching routes:")
    
    # Verify we matched carriers
    assert len(matches) > 0, "No carrier matches generated by spatial matching engine"

    for idx, match in enumerate(matches):
        carrier_type = "Rail (Train)" if match["train_schedule_id"] else "Road (Truck)"
        carrier_name = match["train_schedule"]["train_name"] if match["train_schedule_id"] else match["trip"]["driver_id"]
        print(f"\n  [{idx+1}] Match Option: {carrier_type} - {carrier_name} (Score: {match['score']})")
        print(f"      Status: {match['status']}")
        print(f"      Claude Explanation: {match['explanation']}")

    print("\n==============================================")
    # 6. Shipper Accepts a Match (Let's pick the Rail option to showcase green freight)
    train_match = next((m for m in matches if m["train_schedule_id"] is not None), matches[0])
    match_id = train_match["id"]
    carrier_type = "Rail" if train_match["train_schedule_id"] else "Road"
    print(f"💳 Shipper accepts the recommended {carrier_type} Match (ID: {match_id})...")
    
    accept_resp = client.patch(f"/matches/{match_id}/status", json={
        "status": "ACCEPTED"
    }, headers=shipper_headers)
    
    assert accept_resp.status_code == 200, f"Match acceptance failed: {accept_resp.text}"
    accept_data = accept_resp.json()
    print(f"  - Match Status updated to: {accept_data['status']}")
    print(f"  - Load Status updated to: {accept_data['load']['status']}")
    assert accept_data["status"] == "ACCEPTED"
    assert accept_data["load"]["status"] == "MATCHED"

    print("\n==============================================")
    # 7. Check Ops Dashboard stats
    print("📊 Fetching Ops Dashboard Statistics...")
    stats_resp = client.get("/matches/stats", headers=shipper_headers)
    assert stats_resp.status_code == 200
    stats = stats_resp.json()
    print(f"  - Total Matched Loads: {stats['total_loads_matched']}")
    print(f"  - Total CO2 Emissions Saved: {stats['total_co2_saved_kg']} kg")
    print(f"  - Corridor Activity Breakdown:")
    for corridor in stats["corridor_statistics"]:
        print(f"    * {corridor['name']}: Matched={corridor['matched_count']}, CO2 Saved={corridor['co2_saved']} kg")
    
    assert stats["total_loads_matched"] >= 1
    assert stats["total_co2_saved_kg"] > 0

    print("\n==============================================")
    print("🎉 ALL PRODUCTION BACKEND MATCHING & GEOSPATIAL ENDPOINTS VERIFIED!")
    print("==============================================")

if __name__ == "__main__":
    test_production_matching_flow()
