// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgUrwe-wvGv4hcBdH16_waD_0y0ozXVa0',
    appId: '1:973163516496:web:068fe6cd90b594e15bb755',
    messagingSenderId: '973163516496',
    projectId: 'faraway-f005b',
    authDomain: 'faraway-f005b.firebaseapp.com',
    storageBucket: 'faraway-f005b.firebasestorage.app',
    measurementId: 'G-09KJG8RVSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCtiC4C6kMpxHFI_sxg1-CybRc5EP-XJo',
    appId: '1:973163516496:android:f568850721b284815bb755',
    messagingSenderId: '973163516496',
    projectId: 'faraway-f005b',
    storageBucket: 'faraway-f005b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX04FWKf5xyB4AeoU-s29ERC3FCwtJyXo',
    appId: '1:973163516496:ios:fee50b332fed746e5bb755',
    messagingSenderId: '973163516496',
    projectId: 'faraway-f005b',
    storageBucket: 'faraway-f005b.firebasestorage.app',
    iosClientId: '973163516496-eteespshkjrf0k7p72q6vmdrm4mohouj.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX04FWKf5xyB4AeoU-s29ERC3FCwtJyXo',
    appId: '1:973163516496:ios:fee50b332fed746e5bb755',
    messagingSenderId: '973163516496',
    projectId: 'faraway-f005b',
    storageBucket: 'faraway-f005b.firebasestorage.app',
    iosClientId: '973163516496-eteespshkjrf0k7p72q6vmdrm4mohouj.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgUrwe-wvGv4hcBdH16_waD_0y0ozXVa0',
    appId: '1:973163516496:web:cfb8ee6aa7fa300f5bb755',
    messagingSenderId: '973163516496',
    projectId: 'faraway-f005b',
    authDomain: 'faraway-f005b.firebaseapp.com',
    storageBucket: 'faraway-f005b.firebasestorage.app',
    measurementId: 'G-1Z7BJ8W9KJ',
  );
}
